name: ci

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@9.0.0
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: amazonlinux-2023
            suite: firewalld
          - os: amazonlinux-2023
            suite: iptables
          - os: almalinux-8
            suite: iptables
          - os: almalinux-9
            suite: iptables
          - os: centos-stream-9
            suite: iptables
          - os: debian-11
            suite: ufw
          - os: debian-12
            suite: ufw
          - os: debian-11
            suite: firewalld-dbus
          - os: debian-11
            suite: nftables
          - os: ubuntu-2204
            suite: ufw
          - os: ubuntu-2404
            suite: ufw
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v7
      - name: Install Chef
        uses: actionshub/chef-install@6.0.0
      - name: Install Policyfile
        run: chef install Policyfile.rb
      - name: kitchen
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        run: kitchen test "${{ matrix.suite }}-${{ matrix.os }}"
